name: Daily Sitemap Fetch and Commit

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 拉取 sitemap 文件并命名
      - name: Fetch Sitemap
        run: |
          DATE=$(date +'%Y-%m-%d')  # 格式化当前日期为 年-月-日
          curl -o "sitemap-$DATE.xml" https://itch.io/games/platform-web.xml

      # 提交文件到仓库
      - name: Commit and push the sitemap file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add "sitemap-$(date +'%Y-%m-%d').xml"
          git commit -m "Add sitemap for $(date +'%Y-%m-%d')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用默认的 GitHub token
