name: Sitemap Diff Checker

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨 12 点运行
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub token 进行提交

    - name: Fetch sitemap
      run: |
        curl -o sitemap.xml https://itch.io/sitemap.xml

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        
        if [ -n "$(git status --porcelain)" ]; then
          git add sitemap.xml
          git commit -m "Update sitemap.xml"
          git push
        else
          echo "No changes to commit"
        fi
